### PR TITLE
OCPBUGS-1411: Bump k8s dependencies to 1.25

### PR DESCRIPTION
**Pull request by lobziik**
Update aws-sdk-go, controller-runtime and openshift/api

### CODE REVIEW

**Comment by lobziik** [comment]
@damdo good catch. Updated.

**Review by JoelSpeed — COMMENTED** [review]
/lgtm
/approve

**Comment by JoelSpeed** [comment]
/override ci/prow/e2e-aws-operator
/override ci/prow/e2e-aws-serial

I'm happy that the test failures aren't being caused by this PR

**Pull request merged**
