### PR TITLE
Bug 2072195: Custom DHCP Option Set: empty domain-name is a valid custom domain

### PR DESCRIPTION
**Pull request by damdo**
This PR fixes a bug reported at https://bugzilla.redhat.com/show_bug.cgi?id=2072195 where adding an empty domain-name in a Custom DHCP Option Set wrongfully ends up breaking the CSR validation for nodes created afterwards.

We know that if a DHCP Options Set does not contain a `domain-name` key, then the metadata service, used by the legacy cloud provider to populate Node.Addresses and therefore the CSR, will not contain a domain. We need Machine.Addresses to contain a corresponding value in this case in order to validate the CSR.

Here we return an Address with an explicit empty trailing domain name iff we have DHCP Options Set with no `domain-name` key, which we add as a NodeInternalDNS (and Hostname) (without a trailing '.').

Note: Bug (and fix) reproduction and verification steps are available on the bug report.

Bug Reproduction (0.00 -> 2.15) and Bug resolution Verification (2.15 -> till end):

https://user-images.githubusercontent.com/4902157/167406867-38aba0cd-6826-48d7-8899-5d223ee64ea0.mp4

### CODE REVIEW

**Comment by JoelSpeed** [comment]
Can you please include in the PR description a note on how this has been tested and what results you have seen when testing this

**Comment by damdo** [comment]
@JoelSpeed I've added a bug reproduction and resolution verification video. There are also reproduction steps available on the BZ.

**Review by mdbooth — APPROVED** [review]
/lgtm

**Pull request merged**
