### PR TITLE
OCPBUGS-11524: Add test for multi security groups per machine

### PR DESCRIPTION
**Pull request by damdo**
Adds a test to ensure multiple securityGroups filters can be set for a Machine.

### CODE REVIEW

**Comment by damdo** [comment]
More granular ones like this I'd probably say QE ones right?

**Comment by JoelSpeed** [comment]
Works for me, CC @sunzhaohua2 could you make sure someone is assigned to this to be able to check what Dam is saying in the bug is true, and build a test into your automation

**Pull request merged**
