### PR TITLE
Bug 2040504: Ensure IOPS setting is honoured on all supported block device types

### PR DESCRIPTION
**Pull request by JoelSpeed**
AWS documentation suggests that `IO1`, `IO2` and `GP3` block devices all support a configurable IOPS setting. We are only allowing this for `IO1` right now, so we should make sure that we set the IOPS on other supported types as well.

> The following are the supported values for each volume type:
> - gp3 : 3,000-16,000 IOPS
> - io1 : 100-64,000 IOPS
> - io2 : 100-64,000 IOPS

### CODE REVIEW

**Review by alexander-demichev — APPROVED** [review]
/approve

**Comment by damdo** [comment]
That's because 4.9 is on a different repo. I did a manual cherry pick to that here: https://github.com/openshift/cluster-api-provider-aws/pull/436

**Pull request merged**
